#a git hub action to deploy to repository 'releases' sections
name: ShellScriptUtils - deploy release
run-name: $${{ github.author }} is deploying a release
on:
  push:
    tags:
      - 'v*'

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/runtests.yaml
    with:
      tests-folder: tests
      main-script: runtests.sh
      
  prepare-release:
    name: Deploy release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: preparing release file
        uses: ./.github/workflows/package_files.yaml
        with:
          #create a name: ShellScriptUtils-v<tag>
          destination-filename: ShellScriptUtils-${{ github.ref_name }}

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: ShellScriptUtils-${{ github.ref_name }}
        
  